-- SELECT *
-- from acc_info;
-- SELECT *
-- from out_info;
-- SELECT *
-- from inc_info;
-- SELECT *
-- FROM permits;
-- SELECT *
-- from fout;
-- SELECT *
-- from permits;
-- SELECT table_name
-- FROM information_schema.tables
-- WHERE table_schema = 'public'
-- AND table_type = 'BASE TABLE';
-- SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.columns WHERE TABLE_NAME = 'IBA';
-- SELECT * FROM "IBA";
-- SELECT * FROM incoming
-- SELECT * FROM account_card
-- SELECT * FROM incoming
-- SELECT id,
--     subject,
--     TRUE AS "OI"
-- FROM outgoing
-- UNION ALL
-- SELECT id,
--     topic,
--     FALSE
-- FROM incoming;
-- INSERT INTO incoming(
--         file_path,
--         account_id,
--         type,
--         book_number,
--         book_date,
--         issuing_authority,
--         topic,
--         incoming_number,
--         referral,
--         section,
--         user_id,
--         note,
--         incoming_date
--     )
-- values(
--         null,
--         null,
--         null,
--         null,
--         null,
--         null,
--         null,
--         null,
--         null,
--         null,
--         null,
--         null,
--         null
--     )
-- RETURNING *;
-- INSERT INTO users(name,username,password,role) values ('Developer','admin','admin',0) ;